fieldLayouts:
  8470011e-8fec-43fa-ac62-950957c78681:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 13b98d9b-df3d-4bdf-9d8d-5e1f7d8ac569
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e5abb398-cb9d-4a1a-aca3-ef0a33e904f5 # Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ac8cf94-82c2-4cef-a72d-5c644bcf1a65
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 20ce68cf-b9b5-4f6e-bf08-05a4e6202788
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 67dac100-a6ea-4ec6-abf4-9cdf6c5c80c9 # Meta
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b93a37cb-c346-4a43-9ac2-ea8254dd764e
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: e71dd074-bfae-4993-a90e-e91e86cd2441
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 599cbc97-144a-4ea5-8d7b-36c8ee6a2ab4 # Page
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
