fieldLayouts:
  6b699019-bdaf-40c8-b8fb-0495159784e2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: Question
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f68bd7c8-fdc6-4cd5-85c3-abcbf347d03d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f5e6feb9-0e5a-4f6f-abb8-4959e567fcf0 # Description
            instructions: null
            label: Answer
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da726f21-8b07-409b-a29c-51720d547fa3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 712d6093-348e-45a4-8ef9-c7b6020c6570
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: da2c1459-999f-4626-8409-a261cc57fe6f # FAQ
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
