childBlocks: null
conditions: null
description: ''
enabled: true
field: e5abb398-cb9d-4a1a-aca3-ef0a33e904f5 # Blocks
fieldLayouts:
  5c2e32a0-dec0-46fa-92ca-86058dd7fd6b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a7e88a68-3575-46c4-83d3-f780f3a4468c # Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f82252d-35f0-4d96-9c64-8e639697b521
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ab8a7d5f-03b1-4332-b628-7aa5d22ba0a7 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: afc128a4-ac05-4c6c-bc35-956c3ff1c747
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 57442773-6111-433a-81dc-3f4f5c8c3420 # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b181b0f1-abf8-40db-b865-42d2179c5eee
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0618b72d-81e6-448c-a10f-f719dbcc25f2 # Anchor ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 70eb25ce-3e1a-49d0-90ce-5372594bf9a7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 61f79668-0121-49d3-ba5e-a4b437e3f98b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b3a0e118-0da5-45fd-9667-e7470417ab95 # Remove Padding
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d7367ce-45f8-4945-bf53-2f914deff57d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4ee81767-1055-483d-9f12-0fd4cbc799db # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0036072c-8531-4aa6-9de6-e797bb7aeab3
            userCondition: null
            warning: null
            width: 100
        name: Styles
        uid: e1b44eff-9e4a-4b90-a91c-4edcf2a5274d
        userCondition: null
group: 49716e1e-e28f-4807-9bdd-1d865b61eed8 # Content
groupChildBlockTypes: true
handle: interior
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Interior
topLevel: true
