childBlocks: null
conditions: null
description: ''
enabled: true
field: e5abb398-cb9d-4a1a-aca3-ef0a33e904f5 # Blocks
fieldLayouts:
  ffe99426-aadb-4ff1-8ef9-787c2c3aced4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1c64b57a-53b7-451f-b049-06871277da51 # Media
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72ee9a62-3e51-4a92-bb9f-f051efa62367
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0618b72d-81e6-448c-a10f-f719dbcc25f2 # Anchor ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 94376909-6889-4fb0-bb5d-86fe4719d291
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 89e60c67-43b2-4de1-9323-aa324d0ced55
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4ee81767-1055-483d-9f12-0fd4cbc799db # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4bc3d2ed-b2e8-4d16-b8e5-ed1d95b214fc
            userCondition: null
            warning: null
            width: 100
        name: Styles
        uid: ce8b5f52-354c-488b-8897-ac9d5b2c5fdd
        userCondition: null
group: 49716e1e-e28f-4807-9bdd-1d865b61eed8 # Content
groupChildBlockTypes: true
handle: splitMedia
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Split Media'
topLevel: false
