fieldLayouts:
  5aa267fb-4bea-468f-a4af-aa6b3e944adc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 0cd55fc4-e56c-4feb-a91c-25ce08b95a28
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 04e63c06-2427-411b-80aa-49a42ae9f4d8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 96566380-9446-4366-9af6-a322b82ee411 # Optimized
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e292bbaf-e374-480e-b0df-14b8555e1fd1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f9abc954-4329-4dc6-a381-5b3dae3ca903
        userCondition: null
fs: localUploads
handle: uploads
name: Uploads
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
