columnSuffix: null
contentColumnType: string
fieldGroup: eaf78ba9-edcd-49a0-9c85-9ff04d14d378 # Common
handle: blocks
instructions: null
name: Blocks
searchable: true
settings:
  maxBlocks: null
  maxLevels: null
  maxTopBlocks: null
  minBlocks: null
  minLevels: null
  minTopBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
