columnSuffix: midkaryf
contentColumnType: text
fieldGroup: eaf78ba9-edcd-49a0-9c85-9ff04d14d378 # Common
handle: subheader
instructions: null
name: Subheader
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
